---
- hosts: localhost

  tasks:
  - name: Create group trigger
    hawkular_alerts_group_trigger:
      hawkular_api_hostname: 'localhost'
      hawkular_api_port: 8080
      hawkular_api_auth_token: 'Basic amRvZTpwYXNzd29yZA=='
      tenant: '_system'
      group_id: 'test_group-01'
      name: 'Test Group 01'
      event_text: 'Test group displayed text'
      severity: 'HIGH'
      auto_resolve: true
      state: 'present'
      tags:
        type: node
      conditions:
        - name: 'Test Condition 01'
          trigger_mode: 'FIRING'
          type: 'THRESHOLD'
          data_id: 'test_condition'
          operator: 'GT'
          threshold: 0.8
        - name: 'Test Condition 02'
          trigger_mode: 'AUTORESOLVE'
          type: 'THRESHOLD'
          data_id: 'test_condition'
          operator: 'GT'
          threshold: 0.8
    register: result

  - debug: var=result
