---
- hosts: localhost

  tasks:
  - name: Create group member
    hawkular_alerts_group_member:
      hawkular_api_hostname: 'localhost'
      hawkular_api_port: 8080
      hawkular_api_auth_token: 'Basic amRvZTpwYXNzd29yZA=='
      tenant: '_system'
      group_id: 'test_group-01'
      id: 'member1'
      name: 'Member One'
      description: 'the first member of test_group-01 trigger'
      data_id_map:
        'test_condition': 'test_condition_member1'
      tags:
        nodename: node01
      state: 'present'
    register: result

  - debug: var=result
